# Generated by Django 5.0.7 on 2024-08-24 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interval', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_id', models.IntegerField()),
                ('plan_code', models.CharField(max_length=30)),
                ('invoice_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
