# Generated by Django 5.0.7 on 2024-09-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('abandoned', 'Abandoned'), ('failed', 'Failed'), ('ongoing', 'Ongoing'), ('pending', 'Pending'), ('processing', 'Processing'), ('queued', 'Queued'), ('reversed', 'Reversed'), ('success', 'Success')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField()),
                ('customer_id_or_code', models.CharField(blank=True, null=True)),
                ('email_token', models.CharField()),
                ('subscription_code', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.paymentplan')),
            ],
        ),
    ]
