# Generated by Django 5.0.7 on 2024-09-13 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('abandoned', 'Abandoned'), ('failed', 'Failed'), ('ongoing', 'Ongoing'), ('pending', 'Pending'), ('processing', 'Processing'), ('queued', 'Queued'), ('reversed', 'Reversed'), ('success', 'Success')], default='abandoned', max_length=20)),
                ('channel', models.CharField(max_length=10, blank=True, null=True)),
                ('bank', models.CharField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, null=True)),
                ('last4_card_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('transaction_id', models.CharField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
        ),
    ]
