# Generated by Django 5.0.7 on 2024-08-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant')], default='Tenant', max_length=8, null=True),
        ),
    ]
