# Generated by Django 5.0.7 on 2024-10-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_onboarduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboarduser',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='house_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
