# Generated by Django 5.1.2 on 2024-11-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_onboarduser_options_user_house_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarduser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboard_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
