# Generated by Django 5.1.2 on 2024-11-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_onboarduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarduser',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
