# Generated by Django 5.1.2 on 2024-11-19 12:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_onboarduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_image'),
        ),
    ]
