# Generated by Django 5.0.6 on 2024-07-11 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('reg_license', models.CharField(max_length=100)),
                ('number_of_units', models.PositiveIntegerField()),
                ('rent_price', models.PositiveIntegerField()),
                ('availability', models.BooleanField()),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='house_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
