# Generated by Django 5.1.2 on 2024-11-19 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_houseunit_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='house_image'),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='unit_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='unit_image'),
        ),
    ]
