# Generated by Django 5.1.2 on 2024-10-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'Resolved'), ('PROCESSING', 'In Process'), ('DECLINED', 'Declined')], max_length=100),
        ),
    ]
