# Generated by Django 5.0.7 on 2024-10-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'Resolved'), ('PROCESSING', 'In Process'), ('DECLINED', 'Declined')], default='Processing', max_length=100),
        ),
    ]
