# Generated by Django 5.1.2 on 2024-10-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('PROCESSING', 'In Process'), ('DECLINED', 'Declined')], default='Open', max_length=100),
        ),
    ]
