# Generated by Django 5.1.2 on 2024-10-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Processing', 'Processing'), ('Declined', 'Declined')], default='Open', max_length=100),
        ),
    ]
